In [1]:
import glob
import re
import pandas as pd

In [2]:
fns = glob.glob('/Users/mrenke/data/ds-stressrisk/sub-*/ses-*/func/*.tsv')

In [3]:
reg = re.compile('.*/sub-(?P<subject>[0-9]+)_ses-(?P<session>[0-9]+)_task-risk_run-(?P<run>[0-9]+)_(events.tsv)')

In [4]:
data = []

for fn in fns:
    try:
        data.append(reg.match(fn).groupdict())
        data[-1]['fn'] = fn
    except Exception as e:
        print(f'Problem with {fn}: {e}')

In [5]:
data = pd.DataFrame(data)

In [6]:
data.set_index(['subject', 'session', 'run']).unstack('run')

                                                                fn  \
run                                                              1
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...

                                                                    \
run                                                              2
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...

                                                                    \
run                                                              3
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...

                                                                    \
run                                                              4
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...

                                                                    \
run                                                              5
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...


run                                                              6
subject session
01      1        /Users/mrenke/data/ds-stressrisk/sub-01/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-01/ses-2/...
02      1        /Users/mrenke/data/ds-stressrisk/sub-02/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-02/ses-2/...
03      1        /Users/mrenke/data/ds-stressrisk/sub-03/ses-1/...
...                                                            ...
58      2        /Users/mrenke/data/ds-stressrisk/sub-58/ses-2/...
59      1        /Users/mrenke/data/ds-stressrisk/sub-59/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-59/ses-2/...
61      1        /Users/mrenke/data/ds-stressrisk/sub-61/ses-1/...
        2        /Users/mrenke/data/ds-stressrisk/sub-61/ses-2/...

[108 rows x 6 columns]

In [7]:
reg.match(fns[0]).groupdict()

{'subject': '13', 'session': '2', 'run': '5'}

In [8]:
data['subject'].unique()

array(['13', '14', '22', '25', '49', '40', '47', '24', '23', '12', '46',
       '41', '48', '52', '55', '30', '08', '37', '01', '39', '06', '54',
       '53', '38', '07', '09', '36', '31', '44', '43', '17', '28', '10',
       '26', '19', '21', '42', '45', '27', '18', '11', '16', '29', '34',
       '33', '05', '02', '56', '51', '58', '03', '04', '32', '35', '61',
       '59', '50', '57'], dtype=object)

In [9]:
df = data.set_index(['subject', 'session', 'run']).unstack('run')

subs = df.index.unique('subject')

incomp_subs = []
for s in subs:
    if df.loc[s].shape[0] == 1:
        ses = df.loc[s].index.get_level_values(0).tolist()[0]
        st = [str(s) + ', ses ' + str(ses)]
        incomp_subs.append(st)

In [10]:
incomp_subs

[['06, ses 1'],
 ['07, ses 1'],
 ['08, ses 1'],
 ['11, ses 1'],
 ['27, ses 1'],
 ['29, ses 1'],
 ['33, ses 1'],
 ['56, ses 1']]

In [14]:
from stress_risk.utils.data import get_all_behavior
import numpy as np 

def get_data(bids_folder='/Users/mrenke/data/ds-stressrisk'):
    df = get_all_behavior(bids_folder=bids_folder)
    df['choice'] = df['choice'] == 2.0
    df['p1'] = df['prob1']
    df['p2'] = df['prob2']

    df = add_cond2df(df) # adds 
    df = df.dropna() # automatially removes subs without group assignment
    df = df.reset_index(level= 'session') 
    return df

def add_cond2df(df):
    #df_cond = pd.read_csv('/Users/mrenke/data/ds-stressrisk/StressRiskNum_ConditionAssigned.csv')
    df_cond = pd.read_excel('/Users/mrenke/data/ds-stressrisk/addMeasures/data_combined.xlsx')
    df_c = pd.DataFrame({'subject' : df_cond['SUBID'], 'group': np.asarray(df_cond['condition']).astype(int)})
    df_c = df_c[df_c['subject'] < 100] # drop TMS subs
    gr = []
    for i in range(0,len(df)):
        sub = df.index[i][0] #subject is the first (0th) index
        #print(sub)
        group = df_c['group'][df_c['subject'] == sub]
        if len(group) == 1:
            gr.append(int(group))
        else:
            gr.append(np.NaN)

    df['group'] = gr 

    return df

In [36]:
df = get_data()
df = df.set_index('session', append=True)

In [17]:
subs = df.index.unique('subject')

incomp_subs = []
for s in subs:
    if df.loc[s].shape[0] == 1:
        ses = df.loc[s].index.get_level_values(0).tolist()[0]
        st = [str(s) + ', ses ' + str(ses)]
        incomp_subs.append(st)

In [18]:
incomp_subs

[]

In [21]:
np.shape(subs) # should be: 61 - 11 (excluded)

(50,)

In [37]:
df
# only 11891 rows but 50 * 2 * 120 = 1200, so 109 missing ...?

                                    rt    n1    n2  prob1  prob2  choice  \
subject run trial_nr session
1       1   1        1        0.476974  13.0  10.0   0.55    1.0    True
            2        1        0.505059   8.0   7.0   0.55    1.0    True
            3        1        0.609260  13.0   7.0   0.55    1.0   False
            4        1        0.522144  38.0  28.0   0.55    1.0    True
            5        1        0.608297  16.0  10.0   0.55    1.0   False
...                                ...   ...   ...    ...    ...     ...
61      6   116      2        1.189453  39.0  14.0   0.55    1.0   False
            117      2        0.755411  43.0  20.0   0.55    1.0   False
            118      2        0.905503  34.0  14.0   0.55    1.0    True
            119      2        1.873285  34.0  20.0   0.55    1.0    True
            120      2        0.989251  42.0  28.0   0.55    1.0    True

                              risky_first  chose_risky  n_risky  n_safe  \
subject run trial_nr session
1       1   1        1               True        False     13.0    10.0
            2        1               True        False      8.0     7.0
            3        1               True         True     13.0     7.0
            4        1               True        False     38.0    28.0
            5        1               True         True     16.0    10.0
...                                   ...          ...      ...     ...
61      6   116      2               True         True     39.0    14.0
            117      2               True         True     43.0    20.0
            118      2               True        False     34.0    14.0
            119      2               True        False     34.0    20.0
            120      2               True        False     42.0    28.0

                                  frac  log(risky/safe)   log(n1)  \
subject run trial_nr session
1       1   1        1        1.300000         0.262364  2.564949
            2        1        1.142857         0.133531  2.079442
            3        1        1.857143         0.619039  2.564949
            4        1        1.357143         0.305382  3.637586
            5        1        1.600000         0.470004  2.772589
...                                ...              ...       ...
61      6   116      2        2.785714         1.024504  3.663562
            117      2        2.150000         0.765468  3.761200
            118      2        2.428571         0.887303  3.526361
            119      2        1.700000         0.530628  3.526361
            120      2        1.500000         0.405465  3.737670

                             bin(risky/safe)    p1   p2  group
subject run trial_nr session
1       1   1        1                   32%  0.55  1.0    0.0
            2        1                   20%  0.55  1.0    0.0
            3        1                   56%  0.55  1.0    0.0
            4        1                   32%  0.55  1.0    0.0
            5        1                   44%  0.55  1.0    0.0
...                                      ...   ...  ...    ...
61      6   116      2                   80%  0.55  1.0    0.0
            117      2                   56%  0.55  1.0    0.0
            118      2                   68%  0.55  1.0    0.0
            119      2                   32%  0.55  1.0    0.0
            120      2                   20%  0.55  1.0    0.0

[11891 rows x 17 columns]

In [48]:
df.index
d = df.reset_index()
counts = []
for sub in subs:
    counts.append(np.sum(d['subject'] == sub))

In [49]:
counts
# some subs apparently did not respond to some trials --> less than 120 trials per session (240 total)

[240,
 239,
 238,
 240,
 239,
 240,
 240,
 226,
 237,
 240,
 240,
 240,
 240,
 239,
 240,
 240,
 235,
 240,
 240,
 238,
 239,
 235,
 240,
 240,
 238,
 239,
 238,
 237,
 240,
 240,
 238,
 240,
 240,
 238,
 216,
 222,
 236,
 236,
 240,
 240,
 239,
 240,
 240,
 240,
 240,
 239,
 236,
 240,
 240,
 234]

In [25]:
df = data.set_index(['subject', 'session', 'run']).unstack('run')
# but this is without the subject filtereing from adding the group and then removing NaNs
df.to_csv('behavior_files_df_local_02.tsv')

In [ ]:
# fmriprep
key = 'fmriprep'
ses = '/ses-*'
file_format = '.nii.gz'
fns = glob.glob(op.join(bids_folder,f'derivatives/{key}/sub-*{ses}/func/*{file_format}'))
reg = re.compile('.*/sub-(?P<subject>[0-9]+)_ses-(?P<session>[0-9]+)_task-risk_run-1_space-T1w_desc-preproc_bold.nii.gz') # fmriprep output
data_preproc = get_files_df(fns, reg)
data_preproc = data_preproc.rename(columns={'fn':'preproc_fn'})

data_preproc = data_preproc.set_index('run', append= True).unstack('run')
df = df_raw.join(data_preproc)
df.to_csv('/home/mrenke/git/stress_risk/stress_risk/prepare/preproc_files.csv')